---

name: test-changelog-generation.yml

on:
  workflow_dispatch: {}

  
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Release Notes
        id: vars
        uses: ./.github/workflows/gradle-goal
        with:
          command: |
            echo 'foo=bar' >> $GITHUB_OUTPUT
#            echo 'notes<<RELNOTESEOF' >> $GITHUB_OUTPUT
#            cat CHANGELOG.md >> $GITHUB_OUTPUT
#            printf '\nThis release is based on the following upstream versions:\n\n' >> $GITHUB_OUTPUT
#            ./gradlew -q printUpstreamDependenciesMarkdown >> $GITHUB_OUTPUT
#            echo 'RELNOTESEOF' >> $GITHUB_OUTPUT

      - name: Echo release notes
        run: echo '${{ steps.vars.outputs.foo }}' && echo '${{ steps.vars.outputs.notes }}'
#      - name: Create GitHub Release
#        env:
#          GH_TOKEN: ${{ github.token }}
#        run: |
#          gh release create v1.23 \
#            --title="Dummy Release" \
#            --notes="${{ steps.generate_release_notes.outputs.release_notes }}"
