---

name: test-changelog-generation.yml

on:
  workflow_dispatch: {}

  
jobs:

  generate-release-notes:
    runs-on: ubuntu-latest
    name: Generate the changelog for this release
    outputs:
      notes: ${{ steps.print_release_notes.outputs.notes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: ./.github/workflows/gradle-goal
        with:
          command: ""
      - name: Print Release Notes
        id: print_release_notes
        run: |
          echo 'notes<<RELNOTESEOF' >> $GITHUB_OUTPUT
          cat CHANGELOG.next-release.md >> $GITHUB_OUTPUT
          printf '\nThis release is based on the following upstream versions:\n\n' >> $GITHUB_OUTPUT
          ./gradlew -q printUpstreamDependenciesMarkdown >> $GITHUB_OUTPUT
          echo 'RELNOTESEOF' >> $GITHUB_OUTPUT  
          

  generate-release:
    runs-on: ubuntu-latest
    needs:
      - generate-release-notes
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create v1.25 \
            --title="Dummy Release" \
            --notes='${{needs.generate-release-notes.outputs.notes}}'
