---

name: Update Upstream Dependencies

on:
  workflow_dispatch: {}

permissions:
  contents: read

env:
  GH_TOKEN: ${{ github.token }}
  # this branch will be created / force-pushed for the PRs to update the upstream dependencies
  BRANCH_NAME: update-upstream-agent

jobs:
  update-upstream-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: elastic/oblt-actions/git/setup@v1
        with:
          github-token: ${{ env.GH_TOKEN }}
      - name: Fetch latest opentelemetry-java-instrumentation release
        id: latestOtelRelease
        run: |
          tag_name="$(gh release list --repo https://github.com/open-telemetry/opentelemetry-java-instrumentation --json isLatest,tagName --jq '.[] | select(.isLatest) | .tagName')"
          echo "Tag of the latest opentelemetry-java-instrumentation release is $tag_name"
          echo "tag=$tag_name" >> $GITHUB_OUTPUT
      - name: Update upstream dependencies
        id: dependencyUpdate
        run: |
          ./gradle/update-upstream.sh ${{ steps.latestOtelRelease.outputs.tag }}
          if [[ `git status --porcelain` ]]; then
            echo "Directory contains uncommitted changes, assuming an update happened"
            echo "updated=yes" >> "$GITHUB_OUTPUT"
          else
            echo "Directory doesn't contain uncommitted changes, assuming everything is up to date"
            echo "updated=no" >> "$GITHUB_OUTPUT"
          fi
          git status
      - name: Gradle build without tests to regenerate license files
        if: ${{ steps.dependencyUpdate.outputs.updated == 'yes' }}
        uses: ./.github/workflows/gradle-goal
        with:
          command: "./gradlew build -x test"
      - name: Push branch for version update
        if: ${{ steps.dependencyUpdate.outputs.updated == 'yes' }}
        run: |
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Update upstream dependencies for upstream release ${{ steps.latestOtelRelease.outputs.tag }}"
          git push --set-upstream origin --force
          
        
        
