---

name: Update Upstream Dependencies

on:
  workflow_dispatch: {}

permissions:
  contents: read

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  update-upstream-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch latest opentelemetry-java-instrumentation release
        run: |
          tag_name="$(gh release list --repo https://github.com/open-telemetry/opentelemetry-java-instrumentation --json isLatest,tagName --jq '.[] | select(.isLatest) | .tagName')"
          echo "Tag of the latest opentelemetry-java-instrumentation release is $tag_name"
          echo "tag=$tag_name" >> $GITHUB_OUTPUT
      - name: Update upstream dependencies
        run: |
          gradle/update-upstream.sh
          if [[ `git status --porcelain` ]]; then
            echo "updated=1" >> "$GITHUB_OUTPUT"
          else
            echo "updated=0" >> "$GITHUB_OUTPUT"
          fi
      - name: Gradle build without tests to regenerate license files
        uses: ./.github/workflows/gradle-goal
        with:
          command: "./gradlew build -x test"
